version: '3.8'

services:
  php:
    container_name: php_prod
    user: "1000:1000"
    build:
      dockerfile: ./docker/php/Dockerfile.prod
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
    networks:
      - laravel-production

  nginx:
    container_name: nginx_prod
    build:
      dockerfile: ./docker/nginx/Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - laravel-production

  db:
    container_name: db_prod
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel-production

  redis:
    image: redis:alpine
    container_name: redis_prod
    ports:
      - "6379:6379"
    networks:
      - laravel-production

networks:
  laravel-production: